version: '3'

services:
  test_db:
    build:
      dockerfile: build/postgres/Dockerfile
      context: .
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    volumes:
      - "./scripts/sql:/tmp/sql"
    ports:
      - '6432:5432'
